apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:w6OWh/4If8zOqoMt8pxl28UKeVJeGrynGKS4QCH2PeY25Dp+Dzletw==,iv:lZfBX57cnxttsznEYtC8qs6wWAmLYpDbc4npr7vUlnY=,tag:vQgOOS4mIpa8YwubstLEnQ==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQTjg5RlN5VDRXWlpuSEty
        aWl5SXhVWFp6aVFpVEFIT3ZXVHBDNVZxeDNnCnZiMUpiVDQ2RDQ5MnlZVjVGOUto
        dnowWmh2K25zbmJZdFkzVFF5KzhTY0kKLS0tIEdRdXNOaUNjTGx3TXFURTc5V010
        cWRIVkVNejFjN2pYYlRhckY1d2xMcE0KUONKJMtxkUE41bOuq8brBKft9Z8XiBSs
        C/KF3Q+DUY5BpkNBoNuWUsx+dNpwPClCCF8LJ2hWPNJ+mmQemnbl4g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T21:38:38Z"
  mac: ENC[AES256_GCM,data:ME2EjQBNKoFqiv2EDYMSzv3MBK38XIBSV4LsVVW4Sd+E3ZQ7Qiwdh9E/gFh/Nb48mcnNBF3ReiLlsTb3vdv0GROJ8JJnS1HqeFEdgy9R5tntX0l5nGrziY5zou2z20l/PU1eWGllkgPVJaV5InB393xqEDDslH58hif7R2HVRMg=,iv:duMEodx3C92ovbtHHUj+h89Co/6uW2S59F3efC3EqVU=,tag:vUY4/vxisvzjjTB0N/+kpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
