apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:tjcMxP8Ud9TuEQOaBZSa1J03tpC19KebPTJPMHEqGK3bz2naftZSbA==,iv:2NAchJEJS3uuAvRgIWiAB/DWEGPU9uJLD4AZfZj2WqM=,tag:jYLdEynt3lwA7/VlXGYLMQ==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2R0ZsL2FXOFA1aDVDM2c2
        T3FUNXQ2eHJmejBNNzVBNU5hbzNuZFlTTlFVCjRaNWc2SzRHYW4yclpxYXpLYjVx
        UFNUNXVCcmV4QWRwVkRUQVQ0UE9TQ1UKLS0tIDFCb2pYelAzZkxDcFVqZlV5TStD
        RGlUNXJNbFZoUTlaWnRlb3pXVEkxZ3cKOrGDg4SLozsW9p9qGv/4glIIIo6xCOI0
        3Tn072SMt5OSIfk9WwdNeigZpKakpGo6qFOwPxCSoLbJz/RFAZG0Ww==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T22:20:12Z"
  mac: ENC[AES256_GCM,data:HkQl2Bq3ASLtU8ZzIg0TpOtf9uVX0hEUoG+/Dm5dYeutx1tWT7l9K141xsVFRWlpWdktP8ypEf9vRXnDtclEvzG1Rp15Zhvr6aTtvwlLlzimjepJAdZ/MsVQ0tiSRFRVHNSQsntwHsfo335p1tCKqFGDqY6hDDuTbWbH8tEbUN4=,iv:X1XBZjtq3rEHdKZ8cq5UOUmEn5Fi345nOPSzClQXhG8=,tag:4eOrRqDZ/8Qwcq4E3tKQDw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
