apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:DkPtFWLmEboCe6lKds6DVSOXBDCMertLLK1oS9k+qHn0WQ6GikSPnQ==,iv:JvNlSPBq+NDDFc5SaiYlBdJIImlFg+2m/87jujoeWXY=,tag:wlbZ4OCWecremoKHj86oOg==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNWVFKOG13dHhMWU9hcFZx
        SDRldmozNkdUbi9oQlczL0dpdlQ4eVRzNmtjCmRuMGtjZEwzSTIxSk5OYlc2MUFy
        aEV1K3R3N25GWkNPOTZLNkdoYm9mSWcKLS0tIGlieFZzV3FvTUQ5RVR6cEhvd21Z
        OElRMGZkNnY2ZExmS3kwNlh6aGxIWVUK06lPiget1c9ew8C6siMX9ErCIA5idUtS
        srAFm3y8F+EDa8vhYCie3tvQVupFcf8Fhm5yszjg/qIJXC4OB/K1VQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T21:46:26Z"
  mac: ENC[AES256_GCM,data:UuKIvkNrJxMqsQ2XQSb91PfJ3yBBhlF27cZUSJDeo1OnxlD1VRdXlP3ooePc2wcjjp6YOOUJ12gcmI3rdpI47oSyOd8JHlLbJpzuSh3LkQ32v/iFWgqpTyWJdK33+ImXmu7NKzuSug/faU4x700h60csesxO8LBPdtte296jLFs=,iv:n+f27V0Bo2J5MSOeJ5we+xWLLZEOpbF3AcG12CjdmmI=,tag:+q4uuEF9sZTEeM2U5q3zeA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
