apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:gEatDy5Dtno=,iv:1IWn58NMwUPJaDj0kNYYbat3Zg43ldxcTgys8keoxEw=,tag:0wDt5//qVwffwR9Lc/i6Xw==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQNnc4ajVyOUQvejhVbDND
        Z3hueDBPeElvblNkaSsrekVYQzRsa1k3OHh3CnRnZHI2cGlsR2ViRVVMUU5zaUZ0
        bm0rSWN3cUt2cEo0MWJvcWJwZkRzUmMKLS0tIHl4U0FkS0tNS3lFREdDckxWbXY2
        VlFqU0d5dE9lajFERlp0NTZ4bDVjcXMKG8JaJSZOtBN4xm9mH/R9PZ2Q+UVrhXOq
        a8cZl1AapNe7Ur0fqkGdxsayY9YuB/JyFiYUWbagbA9gSOzlio0IOQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T21:46:26Z"
  mac: ENC[AES256_GCM,data:5yl3UfQpCR1Pkf6+JVJjGJ5QXhFOZ0+goo/1Wkiybq/9sKvaH9uZ6m//Ty2m/CeKl2rUJBuco/VNRa8a3IXxMGzute1drrTSykrmhAdqCTu6Z3InwJnyq1+/G9iuIkupD47dcJD6/ZzAMa77q8G+mB/W7tn+3DT6idIHdWFAyWo=,iv:OhcMdelQGdLTvfcA7pyyDKx6oywVi12ozWvCMJiODbI=,tag:IZiaEC9q+sHWlT/GM1J4uQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
