apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:+MAfBccXxBY=,iv:De7VzaRLTVzm3Nf7vdF5s4WglV/5uaDxf3bI+DaTVp8=,tag:8FNTFyzDMdObHP+F4eAUCA==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFZmp5dEdwVmRoMEtKMGRB
        TUdocGpMdmdHSjhjelZ6cTdpeW1uZC80YjB3CnFIWXNCdCtjdnc2bUptVmdjeGJh
        eitEM0FidXJCV3dVSVY0ZCtKT1lFOHMKLS0tIForUEs3eDR0bDN0eER6NEtEd0Fo
        R2M3Rk83NWY1SU4yYVBoeEl6VS9MT0kKFCIFItrjNFOkFLxQSTSMFP7sSXYFA6ZE
        jtIaYzMG9fk3QrBfmjJNM3EptsTa19gskzutiTDns5WhX207qQy54Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T22:20:12Z"
  mac: ENC[AES256_GCM,data:6Gc+ZnOCvwi/5OsrMb9y3vMSUd7iCL8qW7NZTuveTmZrLM7Pdnx/PBlsxGtDxh6wQF6LjAy8MIeK+eKYWWUEdcUcoq3GrnFGPCQt6cz89k48EuAI1L74gSp4tp++GctYVUubteEQrKo5z9GKoq2QBrkpMyUrlFx9DVMFiFBbW2Q=,iv:CEyx9dX1kZq+uqJg4fM7HcSIHfqentbmLJNmP4R9n3E=,tag:n6AKsF8O1lE4QnL+sjG79Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
