apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:gFnZTwxPUYA=,iv:t9yxFSsPeLkrX2n1IyjoeCG3OsODsgSo1N8xSoZl8SE=,tag:NzhAUJiPcfTjd6Lpv3j9kQ==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKM2UrV3JpeDFPWGtPMTZl
        SHF5N3JobkJ1SG9tY000MkNxZjQ2Z1RyM3djCko0SFNPUTJKdVFaTEQyOHk5TXpa
        YUduNjJST3IyNExZVHE3aDVtSE9UbDgKLS0tIEcvdlpOK2tPQjdvRTBxNkY0OG9x
        MC8xNTZjZ25VSS9mVWU1N1FUMnN2WlkKIm2QBWTNEOC6CaR8gt2cx4r0vsftM4pc
        5G/IOmu5BKX87Nj9dy0ReDOP4CbnVankDNaqoRVXn4yqcfPj6fSa4w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T21:38:38Z"
  mac: ENC[AES256_GCM,data:BV36C4PEosuWMTuGrVhYCt6El3Rf/8oD3Qne5l+gb1Ac9t12ftGQhqrEGFoDAXfcLvvdzb8C57QlXsSvu/f1Abl1jm3YszF21UCVTdTSNPdW8yTIQTOxd4stLwQ9ubzyKjxqGRcXaquOEdGVQHfwNtUuRuO+b7W5wE3jRSrl40M=,iv:Z0SShcCaOaRJtFXDzxHC4069BtNZxZ4hLhsiPBNlE8I=,tag:OFSc3ZmruQWRgFliSVqddw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
