apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:k0XmTw9iwqwFWNwlNJAikQG3TGHFlYbA2DJCTOPPFfI=,iv:tKEFU2ETmQi9UvRIgIrpuOXBUYPJvmBk2fAVm4TAgZI=,tag:kzeLKGxag0byO/J5s/s6Gg==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSQVpPRDF4WlZUcXJiMWZW
        cHlQNVNKbFh6NGtvV3ZEdlFnUGF2QWYzWHpZCng4Z25sZFZ1cW5GcTllZ3ZwdXJU
        K29HdmcvaDlnMGhVTkJTai9WMXJlMDQKLS0tIFU3dVNPTnc0WWFiSzRlempocnRB
        MGtGektWRytVdkg3d29XU3Z4L0pYSVEKrWK2pu73xm6nhcYCAaJynM++q/FHM7dM
        TeHb4IEGNAXczxoPky3XrEuLYXZcXlMW8Zhd6XfXvCgWdhmy3N/Wvg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T21:46:26Z"
  mac: ENC[AES256_GCM,data:x7qfwsaC9GzJKteLvjHnLEwGXu02xQYURZ4Yp+4iyp76R1k4t8ZACR13IsLQb3KzUXgQI0uwNaORYQbDMvYhIKKmV8x7XXc9dK5GNdNwbxCdR0MSS8lBq4lkjPm+eNEIjZJo5BIHoZKWNaImcWDxkYk+lUH6Os22gXF0K9rl0JE=,iv:1vthlR/Rp+7+p/bgHnnIyMlv3JtsOrFf6lGJFLHCgEU=,tag:Jb80LP/RTn2TcrYsRz5Ltg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
