apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:TaSKhnrmhOA15Bgw5mZoqG/KJvMPoZECOQZ6oagRT1A=,iv:CMr08SvkHleB2VkYtvKHMyQ2OE1mSL8w6I649aQkHBw=,tag:7UemJsx4NqOOAfSir9WdHw==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBERDhIVlRCdHF1VzlVN1NP
        cG42QThnME93bVFxaTFkMlZNOWFFU2F4Q1NNCitoMlQwSVFKWFZrc3M5c3huYXo4
        UjFnWDh1dCswTnRDb2xpZkhiUnRuSG8KLS0tIGNNQWlpS0I0ZENDM25nd1lsNm5y
        eUZleUNyRjk2UGFVRkJlcm5PUk0zc00KyyduvpPTKU1zzFAsOwhJx1/VsY7aBE+m
        a0YUiTXtSpIHl/TnszEc4sYhcIrd+NQ7s6jnFLi0roCT6dCPbxVbDg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T21:38:38Z"
  mac: ENC[AES256_GCM,data:4RoLm03A+JEkDLUoIskfv5l2h2u3cMHeLK1ephh20I2liKG0uAmZ1U8UL0bhDIZrvNNNhdTcfomhgk2Hvs+MV5BSVe761d0r1VmuDrdG88jReFnSFfhuTMU7UbnPB33RBTVPmiPOiUQA+4ByQqol2jLrEtR+MeEgP5KK7+yrLd0=,iv:g5Pqa/YMQNWa2js31Oc1o6aH0K9TIFh5nE1oshJMdC4=,tag:gZ3IiyHCjXetq1DKXnSl6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
