apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ZTnlLSie4uLRvC+iGTqbbcjX0hl+YulvxnzVYwfnAwc=,iv:Ksxs3Edf5QFhr3pXuUaGxGAzPVDopYQdIZFeRtP5zJ4=,tag:6Jt8C+vYgeVLUMcV86l2DA==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnTHdPc09pcTRHV283NHJK
        Q0J2NTdpUXV0RzlXd1RSc2JJTnVJZjRDVlg0ClAvbUZBTWo0MDNuWWdQcGhUWVZv
        d1ZlbU5xSS95NUZMQlFoL1pEekx0UkEKLS0tIERSRkk0c3hQVG0yb2xURGRZNEFk
        Y3NNK2Qra2twcUJwZDhSRnZnbWJNYkUKLGzYmpCUnXSjEpObb8oncuXufiROl8M+
        5HYj+kjxpjGS98lkBvfl62se/WxWSnzUpLR5hhVD30NCkZvIdzJnmw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T22:20:12Z"
  mac: ENC[AES256_GCM,data:g2vwkQcG78PVA+rwvJxRO+unvIDl2Ztmzb5btnJIh7ROAzIOWAUypzJQ5unMVLAC+3/3nwccJZMPlebMI8sC5XYEhpKlak+9Naaw1U2kr0hj9r2SZAJqt+DymDY7HTRfGTdzfBzL02cKdmGM3Gz17WxDq2xLGOAmcEkn4kLwP8o=,iv:ygPBWP2oW9ouXUbmBuvAFV2Lg2iqThwGU5pycTaq000=,tag:SwAgaYef6cqMa/jDapXQnw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
