apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:LUKPkqRFttXK6YrPrTTxc6sScn0+jhMaPapAU9cEvizWUnONXtygOfwhljpg+fPNcUNIfBCksHr/KMJYxJ79joS5iXZZ1PM+p89/U3K0ojVM5n/Ko7Cmh/mPh02ZBfnTiU8tc0eCVX1/Q8tdr9cE/DxKlvW8+YQhVEId+2OtQsY9Osfsu2M72/uVRf27/WnMBLe1Ydnu2rfjF+87WvCRp+PPIaFRJwMaDHFzzF4IlZtZuGHL,iv:e+fF9AMzGOHsAFEKGEbCAsMrfR0PfaMdUvICVsOAuFI=,tag:Y2HEtmfpQpgaCWZ4BAkgmg==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDMzNQZVd4b3p5YzFwUUkx
        TncwYmhzejRrU01jT1lBRmVEQ3hxeW1EUEFZClFlTEE1RGUySHpySXcwTDlWSEVK
        VEc4OXFhSm80QWl2RkY4WEFsbUx5YzQKLS0tIDBCS3NVdVFpTDZOb3ZyNHIzcisr
        KytHa1VaSnVKelZFMUdqenZpSEl0b3MKCCV/xubJ52xRm0oAfY0euEzMOHQncbZd
        g6/OWVkmfzl/NHXwh9hoUzPN3G1RI2CENInTYbiYhR6AQU8ytwChwQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T21:38:38Z"
  mac: ENC[AES256_GCM,data:2kVpVtlYyvfPSklXv3lVWSoSLJMLs3fRyMtTn8TY/IIgluUaae6CL27JsDTpfUzbEQm5xh0y6d1olIgpInwfo932uqRollk6gbUEwWz84011YgU7tbgIuxQlSSAXwR9YtsgIpb+yYu0pPYzc6DA9lR2td4f/V7Ilhhbo58VhyfM=,iv:vPKqkAkMs875IrVUijX20Ww4x2VWZbAX6yYXtjT0Jzs=,tag:cofVOU186JQQnciygwMj2Q==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
