apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:nAvxXtOeLM+MhY+JzWThHIOiuSLxzVOdSqqvqligbonkgZLBcJr7aDF188EQkc483BKexwA4sOfy9fhai+yUSKLCWou2inHQb6KUdfaxbetHLki8/VjnQ6AS5kJcQz6GT5sCBvFSPdndzjujXKdPExjnfx76oKvxyIsBj00hyRNCK8MGyB+8gPZBtJI6qEMF2zdg2VogRT1qoYpTqGaOvexZgLiT50CrSd1HYqoqXFJxfkAL,iv:bWWYaEYJbw/iw06/fGsnD+82ZdrJRBvOdNviavcL8v0=,tag:I3hZk4lOvLKdx1il4gW+4Q==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5cHpDR0dlVHJacFY1VDht
        OTliMlQ3WUZVT1hyL0txTlR6RE0vMmtmNVZJCmlyWVB0cTZ5VitEZGp3SlJxQ1Bs
        SlAyWGY5YjR0Z0FnRnlFa2lFM0J5a2cKLS0tIGY3TVVUcHpXWi9TZlV3MXI5ZXNO
        Q3FyaUxrdG9DSmZsZVdya1JzWlZldDgKdJA2aZwuLwxfkDk9as0HdtnxN4dsz+vp
        ZoRcLrtKY3ZsMNt0KJLFw+fuxk+fzcSMfOuTivI6WxeY3JVq316s+w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T21:46:26Z"
  mac: ENC[AES256_GCM,data:NyzIsEJ9LtDyBn83IYKkKfczTCk8MgduARAukmdcHVAQVKDBKK7H9gclgi4CapO3jJUipAwX4T9vmksFBsJVKQeWe5MseK6k9eWF1kkHSoCutRL9BgONqJj19RWemk9o0p2NuLMdmlVz2urTS47smEXMUXVdPf4ngTC5JxwbJwk=,iv:P12tzXBp9RUNbL29c5Uzq9ZguO9KrTUH7EqeRIpCqRk=,tag:Y6iIxSL+cucg7cDbfAvsLg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
