apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:b4HYg/M2zO+N6KKVx3+fSxeUm83EBjylxGqXMojOhn7yLJsczI25WmFLWaLBA4cqkwd8uSGi0zhPFX4nu3fDOTFigF/vJIfS7Q4aCe/DH/AQYkEbUbUSl+dBDB2hwe+U5PgTR6PcgxfyvfFw3culclXYasTHKnK7Px25JZTQKfQsUdPLP2ara8OfSFF3vAh+qYHxfNdO72+Xu01VxGwyC0azI2AvBn/4W2G/T9PLV8xDO3Wx,iv:AXucZSryezi+wVNBz32UhEdabbFjz2uDTNILmFlQLIY=,tag:aufYZGrDeGLoyEia3fA/Lg==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIQkJGQ3hYYm5qaUdINE1h
        bWhPRmNsN3dZRFN1TU9tYW9ROGVvNTJRMDE4Ci9icVhqalBCTnl4TkJkMElqS0Za
        dmpjY1I3SlE0ZExkaGQ5NUJ0RllZVVkKLS0tIDg5S3RJR01jMjN3bWtIanV3bFFS
        bkdKK3FMOUg4cGtBN1d0K2ZRSFFMZ3cKPfdIvtKTAp1qtVqtE/vlJqGZ4WxDfwyt
        vo7FXILPfJMfQrMVTPMQ0Dy+Q6P0IBLO/q7ZKWyfpHeFNBBj3LHLAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T22:20:12Z"
  mac: ENC[AES256_GCM,data:Tzk7vz0Fdk8Zlq1amEF4Pg6EakZrKXgfAmfbI4UNLUpqy7RIeThJj5Fm6r0YwFh+PENmFJfwk10/Bm9hyQ/upmJt7KQ+gyMnmXZ+8PENG4LqKXvReBziRzhrzFDL6I0I4XG9VHG4r018Gu52C4wM110n58cEy17GLf9wz1wt/vc=,iv:MaPmvDeLk9Gg4bfgNApB3vueCorQHkbJ2Itn3I9l7jM=,tag:qYRGs8b2go9aiVXi+J8y5w==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
