apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:7liFZRAeJmeCj65eeIGlXfGFC7k3fbzgbubIypwbWkyY7uq9pvWufg==,iv:8GGs3gfNoxRR4Y+YnPje/j6yfBpzxf2fQg17mKhu/Ro=,tag:qCnMqt5GWhbPCd0cJ+k7Tw==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOVdXRzhURDUxVG52K0Zn
        N0pUR1BlQzR3RG50dFVKRzNUNE9Fb25pUG5NCi9id094L0E4bWxuVjRENTdjU1ZR
        eEgzZVdKNTMwbGxIM3lUNU5JbE1LK2sKLS0tIGV0am9FY3NoeDBlVHJhdXlxWEdB
        S1JtNzJuZllWWVoycjlUWjBzVUdnN1EKvzLpcPTXxVL0ER5O0jA/hHPXgE38d1WO
        TlMxmjei+7yc/AKjtf2hef6pOJuo9D0biLs1amuUpGPyXyXxlxK6gg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T21:38:38Z"
  mac: ENC[AES256_GCM,data:mp7o7YTJyENaHDqZ7uXPsSL1GlJJxI2inawfXUK5TY89Nwmn4mlexamxaAFBzD/97qKb8+7GiPCQ4MbdtxDSLsO/G1EcRfM81IZy2y8AR+ygZqBoxT/PFCQLiF61gGl/eVPRqPW669sIH4/MqbiGmkrCGdN5xo1UoUmOVuIe3KM=,iv:gYPxWbBNe8/lt3XLZw3IgmFtUi767C5wTPkXB6Cr8F4=,tag:KX29PYRpnX+CYv0W85cENQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
