apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:8XbqPxaKlsFmPATDb31OSkTgXqdZUKdowtmAEn6yi92TSMgxLDDsnw==,iv:kG3fvEftVj7WuU5S15Z7YR2KzbzCpjFJJCIHuarp9t8=,tag:PKoHAd7kiJOzW4hDOqEl3Q==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1NEJqOEVpWC9GQ1NCek52
        cE8yUnR5YUVuQWs4NFNOcjdFMDhBR0hRVGlVCi9ybHdIRnlod1liZnJxUGdQcWtB
        UmYrMFZsM1ZlZ3h0L1djTEQxanRUb28KLS0tIE84aG5oTHBoVjhReDhzOU5ZWFA4
        Qzd2d0dYZFNyTDA2blArZ3NKSkFHL28KhUn1Sbx5HeY+5+QRsSR/q9C50mKeicwf
        c0wDK/1owxBlC0AQtvp5QvMkCfZUrKOzyNXn60fXmxUbZ8OpuCaAdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-12T22:20:12Z"
  mac: ENC[AES256_GCM,data:x2jcxWWRpUfUd/e/KB025eA4pn41NCimGQmnCNZjuV5Qi5Sn749Fvf/e5Z0gt06rKcKgAsycfVm4hKnjyE+xPiA0DnGenkIclX02YzezPdQTpf2L3SZC8cN6zZIoUtiFoMa487I01Jwuo3K9F8GE750ublQAkkhIsEdkJHKhWIM=,iv:ATnnhucphw8/Jxk83HKvr6DipxVurArYWpY5W4c8ohw=,tag:/OCqpqYyZzpWPDyX4fCpTQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
