apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:d9k99hofGvRF63aYSmUAAdIxMBnL8yMvEPJzqTeQf8Eqr526MyHVzw==,iv:KS2z/Q314cPKWngPS13AJeP0oxaN8opIZ0ef9ULaefY=,tag:G9T0Hlhr1DaiFg9Annnklw==,type:str]
sops:
  age:
    - recipient: age1753np3vfk99rmd9sqtux5a24hqe4unafpd8n09aazjhnw4wda43s2hgach
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAySXFmN01wcmVObmNzN2lB
        M29LQUJUcmFpQ09hMzVaUUxHNWFFSk0ySUh3CmdJS0lUeW1hRUErdDNWM3RWUWV5
        cXhlU3J3N21nTGtaRjFuUTZxMzdPdmsKLS0tIHFFajBYZ1E2QnBwVVpZcWxFaVdZ
        aUhGNUFiQlRJZmtqV3dYNld4amZmMHMKm4HURtVcktn8s6N5BFSan06zSUriMx1I
        HC6TNXjpNIPI5AzTvj13FjPl1yPyWZAAKcEsNRoFr2UCVhkb2TiRYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-11T21:46:26Z"
  mac: ENC[AES256_GCM,data:PwW5ze9LCZjN/kzrlMt4ZMZ4MjzV2HSJLmrUzqZTUVW2fFh2StUpPSnu0pcAJhx/7jzZGeDEGS2QeVyGJlnyiiTXSkWy8XP6Gpvn+RRl2Qh6CCO6w5d6WqeZrMSQH1CVc1r1x7zyFHUA5ijgOgxxI9vx+eSOKhrjZgwbhCswkbM=,iv:FC/CvlzqatuV7wlb5ZlNvF4GZxBPODBGZltMl5g2A60=,tag:RkJ+PtrwZ8N4kRIlLtI6eg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
