---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.66.93.49:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.66.93.49"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-proxmox-0"
    ipAddress: "10.66.93.50"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:6d:7b:da"
        dhcp: false
        addresses:
          - "10.66.93.50/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.66.93.1"
        mtu: 1500
        vip:
          ip: "10.66.93.49"
  - hostname: "talos-proxmox-1"
    ipAddress: "10.66.93.51"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:c6:0c:2f"
        dhcp: false
        addresses:
          - "10.66.93.51/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.66.93.1"
        mtu: 1500
        vip:
          ip: "10.66.93.49"
  - hostname: "talos-proxmox-2"
    ipAddress: "10.66.93.53"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/ce4c980550dd2ab1b17bbf2b08801c7eb59418eafe8f279833297925d67c7515
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "bc:24:11:e9:dc:17"
        dhcp: false
        addresses:
          - "10.66.93.53/24"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.66.93.1"
        mtu: 1500
        vip:
          ip: "10.66.93.49"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/cluster.yaml"

